"""Configuration package for Project Shri Sudarshan."""

from .settings import settings, Settings
from .prompts import (
    FUNDAMENTALS_ANALYST_PROMPT,
    MACRO_NEWS_ANALYST_PROMPT,
    SENTIMENT_ANALYST_PROMPT,
    TECHNICAL_ANALYST_PROMPT,
    BULLISH_RESEARCHER_PROMPT,
    BEARISH_RESEARCHER_PROMPT,
    DERIVATIVES_STRATEGIST_PROMPT,
    EQUITY_TRADER_PROMPT,
    FNO_TRADER_PROMPT,
    PORTFOLIO_MANAGER_PROMPT,
    RISK_MANAGER_PROMPT,
    REFLECTIVE_AGENT_PROMPT,
)

__all__ = [
    "settings",
    "Settings",
    "FUNDAMENTALS_ANALYST_PROMPT",
    "MACRO_NEWS_ANALYST_PROMPT",
    "SENTIMENT_ANALYST_PROMPT",
    "TECHNICAL_ANALYST_PROMPT",
    "BULLISH_RESEARCHER_PROMPT",
    "BEARISH_RESEARCHER_PROMPT",
    "DERIVATIVES_STRATEGIST_PROMPT",
    "EQUITY_TRADER_PROMPT",
    "FNO_TRADER_PROMPT",
    "PORTFOLIO_MANAGER_PROMPT",
    "RISK_MANAGER_PROMPT",
    "REFLECTIVE_AGENT_PROMPT",
]
